import type { Job } from './types'

function daysAgo(n: number) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const sampleJobs: Job[] = [
  {
    id: 'job-1',
    company: 'Vercel',
    position: 'Senior Frontend Engineer',
    jobUrl: 'https://vercel.com/careers',
    status: 'interview',
    salary: '$180k – $220k',
    location: 'Remote · US',
    stack: ['React', 'Next.js', 'TypeScript'],
    appliedDate: daysAgo(12),
    notes: 'Recruiter call went well. Technical round scheduled.',
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    id: 'job-2',
    company: 'Linear',
    position: 'Product Engineer',
    jobUrl: 'https://linear.app/careers',
    status: 'applied',
    salary: '$160k – $200k',
    location: 'Remote · Worldwide',
    stack: ['React', 'GraphQL', 'Node'],
    appliedDate: daysAgo(6),
    notes: 'Applied via referral from Sarah.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(6),
  },
  {
    id: 'job-3',
    company: 'Stripe',
    position: 'Full Stack Engineer',
    jobUrl: 'https://stripe.com/jobs',
    status: 'wishlist',
    location: 'San Francisco · Hybrid',
    stack: ['Ruby', 'React', 'TypeScript'],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'job-4',
    company: 'Notion',
    position: 'Frontend Engineer',
    jobUrl: 'https://notion.so/careers',
    status: 'offer',
    salary: '$170k – $210k',
    location: 'New York · Hybrid',
    stack: ['React', 'TypeScript', 'WebAssembly'],
    appliedDate: daysAgo(28),
    notes: 'Offer received! Negotiating start date.',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'job-5',
    company: 'Figma',
    position: 'Design Engineer',
    jobUrl: 'https://figma.com/careers',
    status: 'rejected',
    location: 'Remote · US',
    stack: ['React', 'WebGL', 'C++'],
    appliedDate: daysAgo(40),
    notes: 'Rejected after final round. Good feedback for next time.',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(20),
  },
  {
    id: 'job-6',
    company: 'Supabase',
    position: 'Developer Advocate',
    jobUrl: 'https://supabase.com/careers',
    status: 'applied',
    salary: '$130k – $160k',
    location: 'Remote · Worldwide',
    stack: ['PostgreSQL', 'TypeScript', 'Next.js'],
    appliedDate: daysAgo(4),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  },
  {
    id: 'job-7',
    company: 'Wellfound',
    position: 'Software Engineer II',
    jobUrl: 'https://wellfound.com/jobs',
    status: 'interview',
    salary: '$140k – $175k',
    location: 'Remote · US',
    stack: ['Ruby on Rails', 'React'],
    appliedDate: daysAgo(18),
    notes: 'Second interview next week.',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
  {
    id: 'job-8',
    company: 'Raycast',
    position: 'Frontend Engineer',
    jobUrl: 'https://raycast.com/jobs',
    status: 'wishlist',
    location: 'Remote · Europe',
    stack: ['React', 'Swift', 'TypeScript'],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
]
