default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: jobdeck_development

test:
  <<: *default
  database: jobdeck_test

production:
  primary: &primary_production
    <<: *default
    database: jobdeck_production
    username: jobdeck
    password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>

